### ISSUE TITLE
Unused variable imported in graphql.ts file 

### ISSUE THREAD

**Issue by suntoss1997** [raralabs/create-rara-app#3]
Whenever i run yarn dev ; RequestInit an unused variable is imported in graphql.ts file 

![image](https://user-images.githubusercontent.com/40053616/155972634-30f90ff9-c1f9-494b-aa13-27b66f45ec80.png)

**Comment by ctrlx-altf4** [comment]
For more details, you can look at the issue [here](https://github.com/dotansimha/graphql-code-generator/issues/7444). I have updated the version of `@graphql-codegen/typescript-react-query` in create-rara-app. 

Please update the version in your project as well.
